### ISSUE TITLE
Estou com uma dúvida

### ISSUE THREAD

**Issue by lazaropd** [lazaropd/desafio-1-1-003#5]
Tostines vende mais porque é fresquinho ou é fresquinho porque vende mais?

Deixem suas opiniões abaixo

**Comment by Alessandrabuso** [comment]
É um paradoxo muito complexo, preciso pensar.

**Comment by gkimura** [comment]
hahahhaahah o segredo de Tostines

**Comment by wbbatista** [comment]
o que é Tostines?
