### ISSUE TITLE
Definir linguagem de programação

### ISSUE THREAD

**Issue by gkimura** [lazaropd/desafio-1-1-003#8]

**Comment by lazaropd** [comment]
Boa.. bora em Python pra esquentar?

**Comment by gkimura** [comment]
Eu topo

**Comment by lazaropd** [comment]
Fechou.. a Ale está montando uma lógica para nossa funcao. Ela vai compartilhar conosco daqui a pouco. 
Vou colocar lá no kanban do projeto
